### ISSUE TITLE
parse_string doesn't handle escaped backslash correctly

### ISSUE THREAD

**Issue by Jamiras** [leiradel/jsonsax#1]
Simplified example (noticed with path `"C:\folder\"`)
```
{"test": "\\", "foo": "bar"}
```
The callback is passed "`\", `" as the value of "test". I think it's this logic that's wrong:
https://github.com/leiradel/jsonsax/blob/master/jsonsax.c#L164-L167

**Comment by leiradel** [comment]
Thanks for the report, fixed in https://github.com/leiradel/jsonsax/commit/8be177d95279c2e198d91337b33c62e232eb974a
